import type { VouchersProps } from './Campaigns.types'

export const vouchersDefaultProps: VouchersProps = {
  title: 'Promotions & vouchers',
  description: 'Platform-wide discount codes and vouchers',
  newVoucherLabel: '+ New voucher',
  budgetLabel: 'Usage',
  editLabel: 'Edit',
  performanceLabel: 'Performance',
  impressionsLabel: 'Impr',
  ctrLabel: 'CTR',
  redemptionsLabel: 'Redm',
  tabLabels: {
    ACTIVE: 'Active',
    PAUSED: 'Paused',
    EXPIRED: 'Expired',
    DRAFT: 'Draft',
  },
  items: [
    {
      id: 'VCH-001',
      name: 'May Mega Sale',
      type: 'PERCENTAGE',
      category: 'Platform',
      dateRange: 'May 9, 2026 → May 14, 2026',
      status: 'ACTIVE',
      impressions: '—',
      ctr: '—',
      redemptions: '9200',
      budgetSpent: '$42,180',
      budgetTotal: '$80,000',
      budgetPercent: 53,
    },
    {
      id: 'VCH-002',
      name: 'Beauty Spotlight',
      type: 'FIXED_AMOUNT',
      category: 'Beauty',
      dateRange: 'May 6, 2026 → May 20, 2026',
      status: 'ACTIVE',
      impressions: '—',
      ctr: '—',
      redemptions: '2100',
      budgetSpent: '$9,400',
      budgetTotal: '$24,000',
      budgetPercent: 39,
    },
    {
      id: 'VCH-003',
      name: 'Summer Kickoff',
      type: 'PERCENTAGE',
      category: 'Platform',
      dateRange: 'Jun 1, 2026 → Jun 7, 2026',
      status: 'PAUSED',
      impressions: '—',
      ctr: '—',
      redemptions: '0',
      budgetSpent: '$0',
      budgetTotal: '$60,000',
      budgetPercent: 0,
    },
    {
      id: 'VCH-004',
      name: 'Spring Clearance',
      type: 'PERCENTAGE',
      category: 'Platform',
      dateRange: 'Apr 1, 2026 → Apr 10, 2026',
      status: 'EXPIRED',
      impressions: '—',
      ctr: '—',
      redemptions: '31200',
      budgetSpent: '$95,000',
      budgetTotal: '$95,000',
      budgetPercent: 100,
    },
    {
      id: 'VCH-005',
      name: 'Back to School',
      type: 'FIXED_AMOUNT',
      category: 'Education',
      dateRange: 'Aug 1, 2026 → Aug 31, 2026',
      status: 'DRAFT',
      impressions: '—',
      ctr: '—',
      redemptions: '0',
      budgetSpent: '$0',
      budgetTotal: '$50,000',
      budgetPercent: 0,
    },
  ],
}
