import type { CampaignsProps } from './Campaigns.types'

export const campaignsDefaultProps: CampaignsProps = {
  title: 'Promotions & campaigns',
  description: 'Platform-wide and category-targeted programs',
  newCampaignLabel: '+ New campaign',
  budgetLabel: 'Budget',
  editLabel: 'Edit',
  performanceLabel: 'Performance',
  impressionsLabel: 'Impr',
  ctrLabel: 'CTR',
  redemptionsLabel: 'Redm',
  tabLabels: {
    LIVE: 'Live',
    SCHEDULED: 'Scheduled',
    ENDED: 'Ended',
    DRAFT: 'Draft',
  },
  items: [
    {
      id: 'CMP-001',
      name: 'May Mega Sale',
      type: 'Flash',
      category: 'Platform',
      dateRange: 'May 9, 2026 → May 14, 2026',
      status: 'LIVE',
      impressions: '1.2M',
      ctr: '7.0%',
      redemptions: '9.2k',
      budgetSpent: '$42,180',
      budgetTotal: '$80,000',
      budgetPercent: 53,
    },
    {
      id: 'CMP-002',
      name: 'Beauty Spotlight',
      type: 'Banner',
      category: 'Beauty',
      dateRange: 'May 6, 2026 → May 20, 2026',
      status: 'LIVE',
      impressions: '412k',
      ctr: '4.5%',
      redemptions: '2.1k',
      budgetSpent: '$9,400',
      budgetTotal: '$24,000',
      budgetPercent: 39,
    },
    {
      id: 'CMP-003',
      name: 'Summer Kickoff',
      type: 'Flash',
      category: 'Platform',
      dateRange: 'Jun 1, 2026 → Jun 7, 2026',
      status: 'SCHEDULED',
      impressions: '0',
      ctr: '0%',
      redemptions: '0',
      budgetSpent: '$0',
      budgetTotal: '$60,000',
      budgetPercent: 0,
    },
    {
      id: 'CMP-004',
      name: 'Electronics Week',
      type: 'Banner',
      category: 'Electronics',
      dateRange: 'Jun 10, 2026 → Jun 17, 2026',
      status: 'SCHEDULED',
      impressions: '0',
      ctr: '0%',
      redemptions: '0',
      budgetSpent: '$0',
      budgetTotal: '$45,000',
      budgetPercent: 0,
    },
    {
      id: 'CMP-005',
      name: 'Spring Clearance',
      type: 'Flash',
      category: 'Platform',
      dateRange: 'Apr 1, 2026 → Apr 10, 2026',
      status: 'ENDED',
      impressions: '3.8M',
      ctr: '8.2%',
      redemptions: '31.2k',
      budgetSpent: '$95,000',
      budgetTotal: '$95,000',
      budgetPercent: 100,
    },
    {
      id: 'CMP-006',
      name: 'Back to School',
      type: 'Banner',
      category: 'Education',
      dateRange: 'Aug 1, 2026 → Aug 31, 2026',
      status: 'DRAFT',
      impressions: '0',
      ctr: '0%',
      redemptions: '0',
      budgetSpent: '$0',
      budgetTotal: '$50,000',
      budgetPercent: 0,
    },
  ],
}
