/* eslint-disable sonarjs/no-hardcoded-ip */
import type { AuditLogProps } from './AuditLog.types'

export const auditLogDefaultProps: AuditLogProps = {
  title: 'Audit log',
  description: 'Immutable record of admin actions',
  searchPlaceholder: 'Actor, action, target...',
  exportLabel: 'Export CSV',
  emptyStateMessage: 'No log entries match current filters.',
  actorOptions: [
    { value: 'ALL', label: 'Actor : All' },
    { value: 'Admin', label: 'Actor : Admin' },
    { value: 'Moderator', label: 'Actor : Moderator' },
    { value: 'Support', label: 'Actor : Support' },
  ],
  resourceOptions: [
    { value: 'ALL', label: 'Resource : All' },
    { value: 'Seller', label: 'Resource : Seller' },
    { value: 'Product', label: 'Resource : Product' },
    { value: 'Order', label: 'Resource : Order' },
    { value: 'User', label: 'Resource : User' },
    { value: 'Setting', label: 'Resource : Setting' },
    { value: 'Dispute', label: 'Resource : Dispute' },
    { value: 'Campaign', label: 'Resource : Campaign' },
    { value: 'Role', label: 'Resource : Role' },
    { value: 'Session', label: 'Resource : Session' },
  ],
  actionOptions: [
    { value: 'ALL', label: 'Action : All' },
    { value: 'approve_seller', label: 'Action : approve_seller' },
    { value: 'reject_product', label: 'Action : reject_product' },
    { value: 'refund_order', label: 'Action : refund_order' },
    { value: 'suspend_user', label: 'Action : suspend_user' },
    { value: 'update_commission', label: 'Action : update_commission' },
    { value: 'resolve_dispute', label: 'Action : resolve_dispute' },
    { value: 'create_campaign', label: 'Action : create_campaign' },
    { value: 'update_role', label: 'Action : update_role' },
    { value: 'change_setting', label: 'Action : change_setting' },
    { value: 'login', label: 'Action : login' },
  ],
  dateRangeOptions: [
    { value: 'LAST_7_DAYS', label: 'Last 7 days' },
    { value: 'LAST_30_DAYS', label: 'Last 30 days' },
    { value: 'LAST_90_DAYS', label: 'Last 90 days' },
    { value: 'ALL_TIME', label: 'All time' },
  ],
  items: [
    {
      id: 'al-1',
      timestampLabel: 'May 11, 2026',
      timestamp: '2026-05-11',
      actorName: 'Ops Admin',
      actorRole: 'Admin',
      action: 'approve_seller',
      resource: 'Seller',
      target: 'Wei Lim',
      ip: '10.0.0.0',
    },
    {
      id: 'al-2',
      timestampLabel: 'May 11, 2026',
      timestamp: '2026-05-11',
      actorName: 'Sarah K.',
      actorRole: 'Moderator',
      action: 'reject_product',
      resource: 'Product',
      target: 'ORD-100340',
      ip: '10.7.13.5',
    },
    {
      id: 'al-3',
      timestampLabel: 'May 11, 2026',
      timestamp: '2026-05-11',
      actorName: 'Daniel L.',
      actorRole: 'Support',
      action: 'refund_order',
      resource: 'Order',
      target: 'ORD-100339',
      ip: '10.14.26.10',
    },
    {
      id: 'al-4',
      timestampLabel: 'May 11, 2026',
      timestamp: '2026-05-11',
      actorName: 'Mei L.',
      actorRole: 'Admin',
      action: 'suspend_user',
      resource: 'User',
      target: 'Marco Diaz',
      ip: '10.21.39.15',
    },
    {
      id: 'al-5',
      timestampLabel: 'May 11, 2026',
      timestamp: '2026-05-11',
      actorName: 'Iris Cho',
      actorRole: 'Admin',
      action: 'update_commission',
      resource: 'Setting',
      target: 'cr-fash',
      ip: '10.28.52.20',
    },
    {
      id: 'al-6',
      timestampLabel: 'May 11, 2026',
      timestamp: '2026-05-11',
      actorName: 'Ops Admin',
      actorRole: 'Admin',
      action: 'resolve_dispute',
      resource: 'Dispute',
      target: 'DSP-5203',
      ip: '10.35.65.25',
    },
    {
      id: 'al-7',
      timestampLabel: 'May 10, 2026',
      timestamp: '2026-05-10',
      actorName: 'Sarah K.',
      actorRole: 'Moderator',
      action: 'create_campaign',
      resource: 'Campaign',
      target: 'Beauty Spotlight',
      ip: '10.42.78.30',
    },
    {
      id: 'al-8',
      timestampLabel: 'May 10, 2026',
      timestamp: '2026-05-10',
      actorName: 'Daniel L.',
      actorRole: 'Support',
      action: 'update_role',
      resource: 'Role',
      target: 'r-ops',
      ip: '10.49.91.35',
    },
    {
      id: 'al-9',
      timestampLabel: 'May 10, 2026',
      timestamp: '2026-05-10',
      actorName: 'Mei L.',
      actorRole: 'Admin',
      action: 'change_setting',
      resource: 'Setting',
      target: 'payments.cod_enabled',
      ip: '10.56.104.40',
    },
    {
      id: 'al-10',
      timestampLabel: 'May 10, 2026',
      timestamp: '2026-05-10',
      actorName: 'Iris Cho',
      actorRole: 'Admin',
      action: 'login',
      resource: 'Session',
      target: 'ops-admin',
      ip: '10.63.117.45',
    },
    {
      id: 'al-11',
      timestampLabel: 'May 10, 2026',
      timestamp: '2026-05-10',
      actorName: 'Ops Admin',
      actorRole: 'Admin',
      action: 'approve_seller',
      resource: 'Seller',
      target: 'Wei Lim',
      ip: '10.70.130.50',
    },
    {
      id: 'al-12',
      timestampLabel: 'May 10, 2026',
      timestamp: '2026-05-10',
      actorName: 'Sarah K.',
      actorRole: 'Moderator',
      action: 'reject_product',
      resource: 'Product',
      target: 'ORD-100340',
      ip: '10.77.143.55',
    },
    {
      id: 'al-13',
      timestampLabel: 'May 10, 2026',
      timestamp: '2026-05-10',
      actorName: 'Daniel L.',
      actorRole: 'Support',
      action: 'refund_order',
      resource: 'Order',
      target: 'ORD-100339',
      ip: '10.84.156.60',
    },
    {
      id: 'al-14',
      timestampLabel: 'May 10, 2026',
      timestamp: '2026-05-10',
      actorName: 'Mei L.',
      actorRole: 'Admin',
      action: 'suspend_user',
      resource: 'User',
      target: 'Marco Diaz',
      ip: '10.91.169.65',
    },
    {
      id: 'al-15',
      timestampLabel: 'May 10, 2026',
      timestamp: '2026-05-10',
      actorName: 'Iris Cho',
      actorRole: 'Admin',
      action: 'update_commission',
      resource: 'Setting',
      target: 'cr-fash',
      ip: '10.98.182.70',
    },
    {
      id: 'al-16',
      timestampLabel: 'May 10, 2026',
      timestamp: '2026-05-10',
      actorName: 'Ops Admin',
      actorRole: 'Admin',
      action: 'resolve_dispute',
      resource: 'Dispute',
      target: 'DSP-5203',
      ip: '10.105.195.75',
    },
    {
      id: 'al-17',
      timestampLabel: 'May 10, 2026',
      timestamp: '2026-05-10',
      actorName: 'Sarah K.',
      actorRole: 'Moderator',
      action: 'create_campaign',
      resource: 'Campaign',
      target: 'Beauty Spotlight',
      ip: '10.112.208.80',
    },
    {
      id: 'al-18',
      timestampLabel: 'May 10, 2026',
      timestamp: '2026-05-10',
      actorName: 'Daniel L.',
      actorRole: 'Support',
      action: 'update_role',
      resource: 'Role',
      target: 'r-ops',
      ip: '10.119.221.85',
    },
    {
      id: 'al-19',
      timestampLabel: 'May 10, 2026',
      timestamp: '2026-05-10',
      actorName: 'Mei L.',
      actorRole: 'Admin',
      action: 'change_setting',
      resource: 'Setting',
      target: 'payments.cod_enabled',
      ip: '10.126.234.90',
    },
    {
      id: 'al-20',
      timestampLabel: 'May 10, 2026',
      timestamp: '2026-05-10',
      actorName: 'Iris Cho',
      actorRole: 'Admin',
      action: 'login',
      resource: 'Session',
      target: 'ops-admin',
      ip: '10.133.247.95',
    },
  ],
}
