import type { UsersProps } from './Users.types'

export const usersDefaultProps: UsersProps = {
  title: 'Users',
  description: '24 accounts · platform-wide',
  searchPlaceholder: 'Search name or email...',
  exportLabel: 'Export CSV',
  inviteLabel: 'Invite admin',
  emptyStateMessage: 'No users match current filters.',
  roleOptions: [
    { value: 'ALL', label: 'Role : All' },
    { value: 'BUYER', label: 'Role : Buyer' },
    { value: 'SELLER', label: 'Role : Seller' },
    { value: 'MODERATOR', label: 'Role : Moderator' },
    { value: 'SUPPORT', label: 'Role : Support' },
    { value: 'ADMIN', label: 'Role : Admin' },
  ],
  statusOptions: [
    { value: 'ALL', label: 'Status : All' },
    { value: 'ACTIVE', label: 'Status : Active' },
    { value: 'SUSPENDED', label: 'Status : Suspended' },
    { value: 'INVITED', label: 'Status : Invited' },
    { value: 'LOCKED', label: 'Status : Locked' },
  ],
  joinedOptions: [
    { value: 'ANY', label: 'Joined: any' },
    { value: 'LAST_7_DAYS', label: 'Joined: 7d' },
    { value: 'LAST_30_DAYS', label: 'Joined: 30d' },
    { value: 'LAST_90_DAYS', label: 'Joined: 90d' },
  ],
  statusTabs: [
    { value: 'ALL', label: 'All', count: 24 },
    { value: 'ACTIVE', label: 'Active', count: 16 },
    { value: 'SUSPENDED', label: 'Suspended', count: 3 },
    { value: 'INVITED', label: 'Invited', count: 3 },
    { value: 'LOCKED', label: 'Locked', count: 2 },
  ],
  items: [
    {
      id: 'user-1',
      name: 'Alex Tan',
      email: 'alex.tan@halo.market',
      avatarUrl:
        'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=240&q=80',
      avatarFallback: 'AT',
      role: 'BUYER',
      status: 'ACTIVE',
      countryCode: 'SG',
      ordersCount: 0,
      spendLabel: '$80',
      lastSeenLabel: 'May 11, 2026',
      joinedAt: '2026-05-11',
    },
    {
      id: 'user-2',
      name: 'Priya Raman',
      email: 'priya.raman@halo.market',
      avatarUrl:
        'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=240&q=80',
      avatarFallback: 'PR',
      role: 'BUYER',
      status: 'ACTIVE',
      countryCode: 'MY',
      ordersCount: 7,
      spendLabel: '$217',
      lastSeenLabel: 'May 11, 2026',
      joinedAt: '2026-05-11',
    },
    {
      id: 'user-3',
      name: 'Marco Diaz',
      email: 'marco.diaz@halo.market',
      avatarUrl:
        'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=240&q=80',
      avatarFallback: 'MD',
      role: 'BUYER',
      status: 'ACTIVE',
      countryCode: 'ID',
      ordersCount: 14,
      spendLabel: '$354',
      lastSeenLabel: 'May 11, 2026',
      joinedAt: '2026-05-11',
    },
    {
      id: 'user-4',
      name: 'Chloe Nguyen',
      email: 'chloe.nguyen@halo.market',
      avatarUrl:
        'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=240&q=80',
      avatarFallback: 'CN',
      role: 'SELLER',
      status: 'ACTIVE',
      countryCode: 'TH',
      ordersCount: 21,
      spendLabel: '$491',
      lastSeenLabel: 'May 10, 2026',
      joinedAt: '2026-05-10',
    },
    {
      id: 'user-5',
      name: 'Yuki Ito',
      email: 'yuki.ito@halo.market',
      avatarUrl:
        'https://images.unsplash.com/photo-1504593811423-6dd665756598?auto=format&fit=crop&w=240&q=80',
      avatarFallback: 'YI',
      role: 'SELLER',
      status: 'SUSPENDED',
      countryCode: 'PH',
      ordersCount: 28,
      spendLabel: '$628',
      lastSeenLabel: 'May 10, 2026',
      joinedAt: '2026-05-10',
    },
    {
      id: 'user-6',
      name: 'Sam West',
      email: 'sam.west@halo.market',
      avatarUrl:
        'https://images.unsplash.com/photo-1502685104226-ee32379fefbe?auto=format&fit=crop&w=240&q=80',
      avatarFallback: 'SW',
      role: 'MODERATOR',
      status: 'INVITED',
      countryCode: 'VN',
      ordersCount: 35,
      spendLabel: '$765',
      lastSeenLabel: 'May 10, 2026',
      joinedAt: '2026-05-10',
    },
    {
      id: 'user-7',
      name: 'Anya Petrova',
      email: 'anya.petrova@halo.market',
      avatarUrl:
        'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=240&q=80',
      avatarFallback: 'AP',
      role: 'SUPPORT',
      status: 'ACTIVE',
      countryCode: 'JP',
      ordersCount: 42,
      spendLabel: '$902',
      lastSeenLabel: 'May 10, 2026',
      joinedAt: '2026-05-10',
    },
    {
      id: 'user-8',
      name: 'Bima Surya',
      email: 'bima.surya@halo.market',
      avatarUrl:
        'https://images.unsplash.com/photo-1504257432389-52343af06ae3?auto=format&fit=crop&w=240&q=80',
      avatarFallback: 'BS',
      role: 'ADMIN',
      status: 'LOCKED',
      countryCode: 'AE',
      ordersCount: 49,
      spendLabel: '$1,039',
      lastSeenLabel: 'May 10, 2026',
      joinedAt: '2026-05-10',
    },
    {
      id: 'user-9',
      name: 'Wei Lim',
      email: 'wei.lim@halo.market',
      avatarUrl:
        'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=240&q=80',
      avatarFallback: 'WL',
      role: 'BUYER',
      status: 'ACTIVE',
      countryCode: 'SG',
      ordersCount: 56,
      spendLabel: '$1,176',
      lastSeenLabel: 'May 10, 2026',
      joinedAt: '2026-05-10',
    },
    {
      id: 'user-10',
      name: 'Noor Faiz',
      email: 'noor.faiz@halo.market',
      avatarUrl:
        'https://images.unsplash.com/photo-1507591064344-4c6ce005b128?auto=format&fit=crop&w=240&q=80',
      avatarFallback: 'NF',
      role: 'BUYER',
      status: 'ACTIVE',
      countryCode: 'MY',
      ordersCount: 3,
      spendLabel: '$1,313',
      lastSeenLabel: 'May 10, 2026',
      joinedAt: '2026-05-10',
    },
    {
      id: 'user-11',
      name: 'Lia Mendoza',
      email: 'lia.mendoza@halo.market',
      avatarUrl:
        'https://images.unsplash.com/photo-1494790108755-2616b612b786?auto=format&fit=crop&w=240&q=80',
      avatarFallback: 'LM',
      role: 'BUYER',
      status: 'ACTIVE',
      countryCode: 'ID',
      ordersCount: 10,
      spendLabel: '$1,450',
      lastSeenLabel: 'May 10, 2026',
      joinedAt: '2026-05-10',
    },
    {
      id: 'user-12',
      name: 'Tom Brown',
      email: 'tom.brown@halo.market',
      avatarUrl:
        'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=240&q=80',
      avatarFallback: 'TB',
      role: 'SELLER',
      status: 'ACTIVE',
      countryCode: 'TH',
      ordersCount: 17,
      spendLabel: '$1,587',
      lastSeenLabel: 'May 9, 2026',
      joinedAt: '2026-05-09',
    },
  ],
}
