import type { SellerKycProps } from './SellersKyc.types'

export const sellersKycDefaultProps: SellerKycProps = {
  title: 'Sellers & KYC',
  description: 'Approve, suspend and verify merchant accounts',
  awaitingReviewLabel: '5 KYC awaiting review',
  searchPlaceholder: 'Search vendor name...',
  reviewLabel: 'Review',
  emptyMessage: 'No sellers match current filters.',
  statusTabs: [
    { value: 'ALL', label: 'All', count: 7 },
    { value: 'PENDING', label: 'Pending', count: 2 },
    { value: 'APPROVED', label: 'Approved', count: 4 },
    { value: 'SUSPENDED', label: 'Suspended', count: 1 },
  ],
  items: [
    {
      id: 'seller-1',
      vendorName: 'Lumen Audio Official',
      vendorEmail: 'wei@lumen.co',
      ownerName: 'Wei Lim',
      category: 'Audio',
      productsCount: 84,
      gmv: 1240000,
      appliedAtLabel: 'Mar 10, 2021',
      status: 'APPROVED',
    },
    {
      id: 'seller-2',
      vendorName: 'Northbloom Living',
      vendorEmail: 'anya@northbloom.co',
      ownerName: 'Anya P.',
      category: 'Home',
      productsCount: 142,
      gmv: 612000,
      appliedAtLabel: 'May 28, 2022',
      status: 'APPROVED',
    },
    {
      id: 'seller-3',
      vendorName: 'Kairo Tech',
      vendorEmail: 'bima@kairo.id',
      ownerName: 'Bima S.',
      category: 'Electronics',
      productsCount: 56,
      gmv: 218000,
      appliedAtLabel: 'Jan 15, 2023',
      status: 'APPROVED',
    },
    {
      id: 'seller-4',
      vendorName: 'Atelier Noor',
      vendorEmail: 'noor@atelier.my',
      ownerName: 'Noor F.',
      category: 'Fashion',
      productsCount: 312,
      gmv: 3180000,
      appliedAtLabel: 'Aug 1, 2020',
      status: 'APPROVED',
    },
    {
      id: 'seller-5',
      vendorName: 'Verdant Co.',
      vendorEmail: 'lia@verdant.ph',
      ownerName: 'Lia M.',
      category: 'Beauty',
      productsCount: 0,
      gmv: 0,
      appliedAtLabel: 'May 2, 2026',
      status: 'PENDING',
    },
    {
      id: 'seller-6',
      vendorName: 'Hatchery Toys',
      vendorEmail: 'tom@hatchery.sg',
      ownerName: 'Tom B.',
      category: 'Toys',
      productsCount: 0,
      gmv: 0,
      appliedAtLabel: 'May 8, 2026',
      status: 'PENDING',
    },
    {
      id: 'seller-7',
      vendorName: 'Cinder Goods',
      vendorEmail: 'mei@cinder.co',
      ownerName: 'Mei L.',
      category: 'Home',
      productsCount: 22,
      gmv: 41000,
      appliedAtLabel: 'Nov 12, 2024',
      status: 'SUSPENDED',
    },
  ],
  onReview: () => {},
}
