import type { OrdersProps } from './Orders.types'

export const ordersDefaultProps: OrdersProps = {
  title: 'Orders',
  description: 'Platform-wide order management',
  searchPlaceholder: 'Search order ID...',
  viewLabel: 'View',
  emptyMessage: 'No orders match current filters.',
  loading: false,
  activeStatus: 'ALL',
  statusTabs: [
    { value: 'ALL', label: 'All', count: 5 },
    { value: 'PENDING', label: 'Pending', count: 1 },
    { value: 'CONFIRMED', label: 'Confirmed', count: 1 },
    { value: 'PACKING', label: 'Packing', count: 1 },
    { value: 'SHIPPED', label: 'Shipped', count: 1 },
    { value: 'DELIVERED', label: 'Delivered', count: 1 },
    { value: 'CANCELLED', label: 'Cancelled', count: 0 },
  ],
  items: [
    {
      id: 'ord-1001-aaaa-bbbb',
      status: 'PENDING',
      totalAmountLabel: '$42.00',
      sellerCount: 1,
      itemCount: 2,
      createdAtLabel: 'May 20, 2026',
    },
    {
      id: 'ord-1002-cccc-dddd',
      status: 'CONFIRMED',
      totalAmountLabel: '$118.50',
      sellerCount: 2,
      itemCount: 4,
      createdAtLabel: 'May 21, 2026',
    },
    {
      id: 'ord-1003-eeee-ffff',
      status: 'PACKING',
      totalAmountLabel: '$75.00',
      sellerCount: 1,
      itemCount: 3,
      createdAtLabel: 'May 22, 2026',
    },
    {
      id: 'ord-1004-gggg-hhhh',
      status: 'SHIPPED',
      totalAmountLabel: '$210.99',
      sellerCount: 3,
      itemCount: 7,
      createdAtLabel: 'May 23, 2026',
    },
    {
      id: 'ord-1005-iiii-jjjj',
      status: 'DELIVERED',
      totalAmountLabel: '$55.25',
      sellerCount: 1,
      itemCount: 1,
      createdAtLabel: 'May 24, 2026',
    },
  ],
}
