import type { CategoryHierarchyProps } from './CategoryHierarchy.types'

export const categoryHierarchyDefaultProps: CategoryHierarchyProps = {
  title: 'Categories',
  description: 'Hierarchy, slugs, SEO, and merchandising order',
  treeTitle: 'Tree',
  detailsTitle: 'Category details',
  seoTitle: 'SEO',
  statsTitle: 'Stats',
  searchPlaceholder: 'Search categories',
  newCategoryLabel: 'New category',
  saveLabel: 'Save changes',
  saveLoadingLabel: 'Saving...',
  cancelLabel: 'Cancel',
  deleteLabel: 'Delete category',
  deleteLoadingLabel: 'Deleting...',
  displayNameLabel: 'Display name',
  slugLabel: 'Slug',
  parentLabel: 'Parent',
  sortOrderLabel: 'Sort order',
  iconLabel: 'Icon (lucide)',
  featuredLabel: 'Featured',
  showOnHomeLabel: 'Show on home',
  metaTitleLabel: 'Meta title',
  metaDescriptionLabel: 'Meta description',
  canonicalUrlLabel: 'Canonical URL',
  rootParentLabel: '—',
  productsStatLabel: 'Products',
  liveVendorsStatLabel: 'Live vendors',
  gmv30dStatLabel: 'GMV (30d)',
  emptyStateMessage: 'Select category to edit details.',
  emptyTreeMessage: 'No categories yet. Create first category to start hierarchy.',
  noSearchResultsMessage: 'No categories match search.',
  newCategoryName: 'New category',
  newCategorySlug: 'new-category',
  newCategoryMetaDescription: 'Add category SEO copy.',
  defaultMetaTitleSuffix: 'Halo Market',
  unsavedChangesMessage: 'You have unsaved changes. Discard them and switch categories?',
  cancelChangesMessage: 'Discard unsaved changes for this category?',
  deleteCategoryMessage: 'Delete "{name}"?',
  deleteCategoryWithChildrenMessage:
    'Delete "{name}" and {count} nested subcategories? This cannot be undone.',
  nameRequiredMessage: 'Display name is required.',
  slugRequiredMessage: 'Slug is required.',
  canonicalUrlRequiredMessage: 'Canonical URL is required.',
  duplicateSlugMessage: 'Slug must be unique.',
  invalidCanonicalUrlMessage: 'Canonical URL must be relative path or valid http(s) URL.',
  negativeSortOrderMessage: 'Sort order cannot be negative.',
  invalidParentMessage: 'Parent category is invalid.',
  saveErrorMessage: 'Save failed. Try again.',
  deleteErrorMessage: 'Delete failed. Try again.',
  expandedCategoryIds: ['electronics', 'fashion'],
  categories: [
    {
      id: 'electronics',
      name: 'Electronics',
      slug: 'electronics',
      parentId: null,
      sortOrder: 1,
      icon: 'Cpu',
      featured: true,
      metaTitle: 'Electronics - Halo Market',
      metaDescription: 'Phones, laptops, and smart devices from verified sellers.',
      canonicalUrl: '/c/electronics',
      stats: {
        products: '8,942',
        liveVendors: '214',
        gmv30d: '$428k',
      },
      children: [
        {
          id: 'audio',
          name: 'Audio',
          slug: 'audio',
          parentId: 'electronics',
          sortOrder: 1,
          icon: 'Headphones',
          featured: false,
          metaTitle: 'Audio - Halo Market',
          metaDescription: 'Headphones, speakers, and accessories.',
          canonicalUrl: '/c/electronics/audio',
          stats: {
            products: '1,932',
            liveVendors: '64',
            gmv30d: '$84k',
          },
          children: [],
        },
        {
          id: 'mobile',
          name: 'Mobile',
          slug: 'mobile',
          parentId: 'electronics',
          sortOrder: 2,
          icon: 'Smartphone',
          featured: true,
          metaTitle: 'Mobile - Halo Market',
          metaDescription: 'Phones, accessories, and repair essentials.',
          canonicalUrl: '/c/electronics/mobile',
          stats: {
            products: '2,871',
            liveVendors: '92',
            gmv30d: '$149k',
          },
          children: [],
        },
        {
          id: 'computers',
          name: 'Computers',
          slug: 'c1c',
          parentId: 'electronics',
          sortOrder: 3,
          icon: 'Laptop',
          featured: true,
          metaTitle: 'Computers - Halo Market',
          metaDescription:
            'Shop computers on Halo Market. Verified sellers, fast shipping, secure checkout.',
          canonicalUrl: '/c/c1c',
          stats: {
            products: '1,284',
            liveVendors: '86',
            gmv30d: '$184k',
          },
          children: [],
        },
      ],
    },
    {
      id: 'fashion',
      name: 'Fashion',
      slug: 'fashion',
      parentId: null,
      sortOrder: 2,
      icon: 'Shirt',
      featured: true,
      metaTitle: 'Fashion - Halo Market',
      metaDescription: 'Men, women, and kids apparel with seasonal edits.',
      canonicalUrl: '/c/fashion',
      stats: {
        products: '6,228',
        liveVendors: '173',
        gmv30d: '$312k',
      },
      children: [
        {
          id: 'men',
          name: 'Men',
          slug: 'men',
          parentId: 'fashion',
          sortOrder: 1,
          icon: 'PersonStanding',
          featured: false,
          metaTitle: 'Men - Halo Market',
          metaDescription: 'Menswear, shoes, and travel-ready staples.',
          canonicalUrl: '/c/fashion/men',
          stats: {
            products: '1,884',
            liveVendors: '74',
            gmv30d: '$96k',
          },
          children: [],
        },
        {
          id: 'women',
          name: 'Women',
          slug: 'women',
          parentId: 'fashion',
          sortOrder: 2,
          icon: 'Sparkles',
          featured: true,
          metaTitle: 'Women - Halo Market',
          metaDescription: 'Ready-to-wear, handbags, and designer edits.',
          canonicalUrl: '/c/fashion/women',
          stats: {
            products: '2,104',
            liveVendors: '81',
            gmv30d: '$118k',
          },
          children: [],
        },
        {
          id: 'kids',
          name: 'Kids',
          slug: 'kids',
          parentId: 'fashion',
          sortOrder: 3,
          icon: 'ToyBrick',
          featured: false,
          metaTitle: 'Kids - Halo Market',
          metaDescription: 'Kidswear, shoes, and school essentials.',
          canonicalUrl: '/c/fashion/kids',
          stats: {
            products: '1,026',
            liveVendors: '42',
            gmv30d: '$44k',
          },
          children: [],
        },
      ],
    },
    {
      id: 'home-living',
      name: 'Home & Living',
      slug: 'home-living',
      parentId: null,
      sortOrder: 3,
      icon: 'Lamp',
      featured: true,
      metaTitle: 'Home & Living - Halo Market',
      metaDescription: 'Furniture, decor, and everyday household goods.',
      canonicalUrl: '/c/home-living',
      stats: {
        products: '4,119',
        liveVendors: '121',
        gmv30d: '$206k',
      },
      children: [],
    },
    {
      id: 'beauty',
      name: 'Beauty',
      slug: 'beauty',
      parentId: null,
      sortOrder: 4,
      icon: 'Gem',
      featured: false,
      metaTitle: 'Beauty - Halo Market',
      metaDescription: 'Skincare, fragrance, and salon-grade tools.',
      canonicalUrl: '/c/beauty',
      stats: {
        products: '2,340',
        liveVendors: '88',
        gmv30d: '$121k',
      },
      children: [],
    },
    {
      id: 'grocery',
      name: 'Grocery',
      slug: 'grocery',
      parentId: null,
      sortOrder: 5,
      icon: 'ShoppingBasket',
      featured: false,
      metaTitle: 'Grocery - Halo Market',
      metaDescription: 'Shelf staples, pantry boxes, and premium snacks.',
      canonicalUrl: '/c/grocery',
      stats: {
        products: '1,590',
        liveVendors: '51',
        gmv30d: '$93k',
      },
      children: [],
    },
    {
      id: 'sports',
      name: 'Sports',
      slug: 'sports',
      parentId: null,
      sortOrder: 6,
      icon: 'Dumbbell',
      featured: false,
      metaTitle: 'Sports - Halo Market',
      metaDescription: 'Training gear, recovery tools, and outdoor essentials.',
      canonicalUrl: '/c/sports',
      stats: {
        products: '1,102',
        liveVendors: '39',
        gmv30d: '$58k',
      },
      children: [],
    },
  ],
}
