import type { RefundsProps } from './Disputes.types'

export const refundsDefaultProps: RefundsProps = {
  title: 'Refunds & disputes',
  description: 'Resolve cases between buyers and sellers',
  searchPlaceholder: 'Refund ID or buyer...',
  openLabel: 'Open',
  summaryLabel: 'cases',
  filtersLabel: 'Filters',
  emptyStateMessage: 'No disputes match current filters.',
  priorityOptions: [
    { value: 'ALL', label: 'All' },
    { value: 'HIGH', label: 'High priority' },
    { value: 'MEDIUM', label: 'Medium priority' },
    { value: 'LOW', label: 'Low priority' },
  ],
  statusOptions: [
    { value: 'ALL', label: 'Status' },
    { value: 'REQUESTED', label: 'Requested' },
    { value: 'REVIEWING', label: 'Reviewing' },
    { value: 'APPROVED', label: 'Approved' },
    { value: 'REJECTED', label: 'Rejected' },
    { value: 'REFUNDED', label: 'Refunded' },
    { value: 'CLOSED', label: 'Closed' },
  ],
  queueOptions: [
    { value: 'ALL', label: 'Queue' },
    { value: 'OPS', label: 'Ops' },
    { value: 'RISK', label: 'Risk' },
    { value: 'SUPPORT', label: 'Support' },
  ],
  resolutionOptions: [
    { value: 'ALL', label: 'Resolution' },
    { value: 'UNRESOLVED', label: 'Unresolved' },
    { value: 'BUYER_REFUND', label: 'Refunded buyer' },
    { value: 'SELLER_CLOSED', label: 'Closed seller' },
  ],
  items: [
    {
      id: 'DSP-5200',
      orderId: 'ORD-100340',
      buyerName: 'Alex Tan',
      sellerName: 'Lumen Audio',
      amountLabel: '$9',
      reason: 'Item not received',
      openedAtLabel: 'May 11, 2026',
      status: 'REQUESTED',
      priority: 'HIGH',
      queue: 'OPS',
      resolution: 'UNRESOLVED',
      note: 'Carrier scan stalled after dispatch. Buyer requests refund.',
      ownerLabel: 'Owner · Ops Admin',
      timelineLabel: 'Opened 2h ago',
    },
    {
      id: 'DSP-5201',
      orderId: 'ORD-100341',
      buyerName: 'Priya R.',
      sellerName: 'Northbloom Living',
      amountLabel: '$296',
      reason: 'Item not as described',
      openedAtLabel: 'May 11, 2026',
      status: 'REVIEWING',
      priority: 'MEDIUM',
      queue: 'SUPPORT',
      resolution: 'UNRESOLVED',
      note: 'Evidence request sent to seller. Awaiting product photos.',
      ownerLabel: 'Owner · Seller Support',
      timelineLabel: 'Needs seller evidence',
    },
    {
      id: 'DSP-5202',
      orderId: 'ORD-100342',
      buyerName: 'Marco D.',
      sellerName: 'Kairo Tech',
      amountLabel: '$261',
      reason: 'Damaged on arrival',
      openedAtLabel: 'May 10, 2026',
      status: 'REQUESTED',
      priority: 'LOW',
      queue: 'OPS',
      resolution: 'UNRESOLVED',
      note: 'Packaging photos uploaded. Auto-routing to claims queue.',
      ownerLabel: 'Owner · Ops Admin',
      timelineLabel: 'Waiting carrier response',
    },
    {
      id: 'DSP-5203',
      orderId: 'ORD-100343',
      buyerName: 'Chloe N.',
      sellerName: 'Atelier Noor',
      amountLabel: '$356',
      reason: 'Wrong item shipped',
      openedAtLabel: 'May 10, 2026',
      status: 'REVIEWING',
      priority: 'HIGH',
      queue: 'RISK',
      resolution: 'UNRESOLVED',
      note: 'High-value repeat complaint. Escalated to risk review.',
      ownerLabel: 'Owner · Risk Ops',
      timelineLabel: 'Escalated 45m ago',
    },
    {
      id: 'DSP-5204',
      orderId: 'ORD-100344',
      buyerName: 'Yuki I.',
      sellerName: 'Verdant Co.',
      amountLabel: '$330',
      reason: 'Refund not issued',
      openedAtLabel: 'May 10, 2026',
      status: 'REFUNDED',
      priority: 'MEDIUM',
      queue: 'SUPPORT',
      resolution: 'BUYER_REFUND',
      note: 'Refund confirmed. Funds returning in 3-5 business days.',
      ownerLabel: 'Owner · Seller Support',
      timelineLabel: 'Resolved yesterday',
    },
    {
      id: 'DSP-5205',
      orderId: 'ORD-100345',
      buyerName: 'Sam W.',
      sellerName: 'Lumen Audio',
      amountLabel: '$972',
      reason: 'Quality below standard',
      openedAtLabel: 'May 10, 2026',
      status: 'CLOSED',
      priority: 'HIGH',
      queue: 'RISK',
      resolution: 'SELLER_CLOSED',
      note: 'Seller rebuttal accepted. Case closed with audit trail.',
      ownerLabel: 'Owner · Risk Ops',
      timelineLabel: 'Closed yesterday',
    },
    {
      id: 'DSP-5206',
      orderId: 'ORD-100346',
      buyerName: 'Alex Tan',
      sellerName: 'Northbloom Living',
      amountLabel: '$243',
      reason: 'Item not received',
      openedAtLabel: 'May 9, 2026',
      status: 'REQUESTED',
      priority: 'MEDIUM',
      queue: 'OPS',
      resolution: 'UNRESOLVED',
      note: 'Buyer requested faster refund path before delivery window ends.',
      ownerLabel: 'Owner · Ops Admin',
      timelineLabel: 'Opened yesterday',
    },
    {
      id: 'DSP-5207',
      orderId: 'ORD-100347',
      buyerName: 'Priya R.',
      sellerName: 'Kairo Tech',
      amountLabel: '$104',
      reason: 'Item not as described',
      openedAtLabel: 'May 9, 2026',
      status: 'REVIEWING',
      priority: 'LOW',
      queue: 'SUPPORT',
      resolution: 'UNRESOLVED',
      note: 'Support comparing listing copy against received unit photos.',
      ownerLabel: 'Owner · Seller Support',
      timelineLabel: 'Review in progress',
    },
    {
      id: 'DSP-5208',
      orderId: 'ORD-100348',
      buyerName: 'Marco D.',
      sellerName: 'Atelier Noor',
      amountLabel: '$243',
      reason: 'Damaged on arrival',
      openedAtLabel: 'May 9, 2026',
      status: 'REQUESTED',
      priority: 'HIGH',
      queue: 'OPS',
      resolution: 'UNRESOLVED',
      note: 'Fragile item claim. Packing slip and breakage video attached.',
      ownerLabel: 'Owner · Ops Admin',
      timelineLabel: 'Awaiting seller response',
    },
    {
      id: 'DSP-5209',
      orderId: 'ORD-100349',
      buyerName: 'Chloe N.',
      sellerName: 'Verdant Co.',
      amountLabel: '$260',
      reason: 'Wrong item shipped',
      openedAtLabel: 'May 9, 2026',
      status: 'REVIEWING',
      priority: 'MEDIUM',
      queue: 'RISK',
      resolution: 'UNRESOLVED',
      note: 'Second case linked to same seller SKU. Risk review open.',
      ownerLabel: 'Owner · Risk Ops',
      timelineLabel: 'Escalated 1d ago',
    },
    {
      id: 'DSP-5210',
      orderId: 'ORD-100350',
      buyerName: 'Yuki I.',
      sellerName: 'Lumen Audio',
      amountLabel: '$318',
      reason: 'Refund not issued',
      openedAtLabel: 'May 8, 2026',
      status: 'REFUNDED',
      priority: 'LOW',
      queue: 'SUPPORT',
      resolution: 'BUYER_REFUND',
      note: 'Gateway reversal completed. Buyer confirmation received.',
      ownerLabel: 'Owner · Seller Support',
      timelineLabel: 'Resolved 2d ago',
    },
    {
      id: 'DSP-5211',
      orderId: 'ORD-100351',
      buyerName: 'Sam W.',
      sellerName: 'Northbloom Living',
      amountLabel: '$972',
      reason: 'Quality below standard',
      openedAtLabel: 'May 8, 2026',
      status: 'CLOSED',
      priority: 'HIGH',
      queue: 'RISK',
      resolution: 'SELLER_CLOSED',
      note: 'Internal review found listing evidence adequate. Seller cleared.',
      ownerLabel: 'Owner · Risk Ops',
      timelineLabel: 'Closed 2d ago',
    },
  ],
}
