import type { ProductApprovalProps } from './ProductApproval.types'

export const productApprovalDefaultProps: ProductApprovalProps = {
  title: 'Product moderation',
  description: 'Approve, reject, and act on reported listings',
  searchPlaceholder: 'Search listing title...',
  approveLabel: 'Approve',
  rejectLabel: 'Reject',
  approveDialogTitle: 'Approve listing(s)',
  approveDialogDescription: 'Listings become live immediately.',
  rejectDialogTitle: 'Reject listing(s)',
  rejectDialogDescription: 'Listings stay hidden until seller resubmits.',
  reasonLabel: 'Reason',
  reasonPlaceholder: 'Required — recorded in the audit log.',
  reasonHint: 'This action will be logged with your account, IP, and timestamp.',
  statusTabs: [
    { value: 'PENDING', label: 'Pending', count: 6 },
    { value: 'REPORTED', label: 'Reported', count: 5 },
    { value: 'APPROVED', label: 'Approved', count: 4 },
    { value: 'REJECTED', label: 'Rejected', count: 3 },
  ],
  items: [
    {
      id: 'listing-1',
      title: 'Wireless ANC Headphones — Studio Edition',
      sellerName: 'Lumen Audio',
      submittedAtLabel: 'May 11, 2026',
      priceLabel: '$9',
      status: 'PENDING',
      flagsLabel: '—',
      reasonTags: [{ id: 'counterfeit', label: 'Counterfeit risk' }],
      stockLabel: 'Stock 5',
      soldLabel: 'Sold 50',
      ratingLabel: 'Rating 4',
      images: [
        {
          id: 'img-1',
          src: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=900&q=80',
          alt: 'Headphones hero image',
        },
        {
          id: 'img-2',
          src: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80',
          alt: 'Forest art image',
        },
        {
          id: 'img-3',
          src: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80',
          alt: 'Beach art image',
        },
        {
          id: 'img-4',
          src: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=900&q=80',
          alt: 'Lifestyle product image',
        },
      ],
    },
    {
      id: 'listing-2',
      title: 'Linen Lounge Set, Oversized Fit',
      sellerName: 'Northbloom Living',
      submittedAtLabel: 'May 11, 2026',
      priceLabel: '$22',
      status: 'PENDING',
      flagsLabel: '—',
      reasonTags: [],
      stockLabel: 'Stock 18',
      soldLabel: 'Sold 32',
      ratingLabel: 'Rating 5',
      images: [
        {
          id: 'img-5',
          src: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80',
          alt: 'Linen set image',
        },
      ],
    },
    {
      id: 'listing-3',
      title: 'Mechanical Keyboard, Hot-Swap 75%',
      sellerName: 'Kairo Tech',
      submittedAtLabel: 'May 10, 2026',
      priceLabel: '$35',
      status: 'PENDING',
      flagsLabel: '—',
      reasonTags: [],
      stockLabel: 'Stock 14',
      soldLabel: 'Sold 18',
      ratingLabel: 'Rating 4',
      images: [
        {
          id: 'img-6',
          src: 'https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&w=900&q=80',
          alt: 'Keyboard image',
        },
      ],
    },
    {
      id: 'listing-4',
      title: 'Ceramic Pour-Over Coffee Set',
      sellerName: 'Atelier Noor',
      submittedAtLabel: 'May 10, 2026',
      priceLabel: '$48',
      status: 'PENDING',
      flagsLabel: '—',
      reasonTags: [{ id: 'imagery', label: 'Bad imagery' }],
      stockLabel: 'Stock 11',
      soldLabel: 'Sold 21',
      ratingLabel: 'Rating 4',
      images: [
        {
          id: 'img-7',
          src: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80',
          alt: 'Coffee set image',
        },
      ],
    },
    {
      id: 'listing-5',
      title: 'Minimalist Leather Card Holder',
      sellerName: 'Verdant Co.',
      submittedAtLabel: 'May 10, 2026',
      priceLabel: '$61',
      status: 'PENDING',
      flagsLabel: '—',
      reasonTags: [],
      stockLabel: 'Stock 7',
      soldLabel: 'Sold 12',
      ratingLabel: 'Rating 4',
      images: [
        {
          id: 'img-8',
          src: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=900&q=80',
          alt: 'Card holder image',
        },
      ],
    },
    {
      id: 'listing-6',
      title: 'Smart Desk Lamp with USB-C',
      sellerName: 'Lumen Audio',
      submittedAtLabel: 'May 10, 2026',
      priceLabel: '$74',
      status: 'PENDING',
      flagsLabel: '—',
      reasonTags: [],
      stockLabel: 'Stock 26',
      soldLabel: 'Sold 41',
      ratingLabel: 'Rating 5',
      images: [
        {
          id: 'img-9',
          src: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80',
          alt: 'Desk lamp image',
        },
      ],
    },
    {
      id: 'listing-7',
      title: 'Portable Blender Bottle',
      sellerName: 'Nova Daily',
      submittedAtLabel: 'May 9, 2026',
      priceLabel: '$29',
      status: 'REPORTED',
      flagsLabel: '2',
      reasonTags: [{ id: 'misleading-title', label: 'Misleading title' }],
      stockLabel: 'Stock 20',
      soldLabel: 'Sold 44',
      ratingLabel: 'Rating 3',
      images: [
        {
          id: 'img-10',
          src: 'https://images.unsplash.com/photo-1577805947697-89e18249d767?auto=format&fit=crop&w=900&q=80',
          alt: 'Portable blender image',
        },
      ],
    },
    {
      id: 'listing-8',
      title: 'Vintage Brass Wall Sconce',
      sellerName: 'Wren House',
      submittedAtLabel: 'May 8, 2026',
      priceLabel: '$58',
      status: 'APPROVED',
      flagsLabel: '—',
      reasonTags: [],
      stockLabel: 'Stock 9',
      soldLabel: 'Sold 16',
      ratingLabel: 'Rating 5',
      images: [
        {
          id: 'img-11',
          src: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=900&q=80',
          alt: 'Wall sconce image',
        },
      ],
    },
    {
      id: 'listing-9',
      title: 'Protein Cookie Sampler Pack',
      sellerName: 'Peak Pantry',
      submittedAtLabel: 'May 8, 2026',
      priceLabel: '$17',
      status: 'REJECTED',
      flagsLabel: '1',
      reasonTags: [{ id: 'pricing', label: 'Pricing anomaly' }],
      stockLabel: 'Stock 33',
      soldLabel: 'Sold 9',
      ratingLabel: 'Rating 2',
      images: [
        {
          id: 'img-12',
          src: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=900&q=80',
          alt: 'Cookie sampler image',
        },
      ],
    },
  ],
}
