export {
  AffiliateStatus,
  CouponScope,
  CouponStatus,
  CouponType,
  FlashSaleSlotStatus,
  FlashSaleStatus,
  PlatformVoucherStatus,
  PlatformVoucherType,
  type AffiliateStatus as AffiliateStatusType,
  type CouponScope as CouponScopeType,
  type CouponStatus as CouponStatusType,
  type CouponType as CouponTypeType,
  type FlashSaleSlotStatus as FlashSaleSlotStatusType,
  type FlashSaleStatus as FlashSaleStatusType,
  type PlatformVoucherStatus as PlatformVoucherStatusType,
  type PlatformVoucherType as PlatformVoucherTypeType,
} from '../generated/enums'
