import {
  BookOpen,
  CarFront,
  Dumbbell,
  Laptop,
  PawPrint,
  ShieldCheck,
  Shirt,
  ShoppingBasket,
  Smartphone,
  Sparkles,
  Sofa,
  Headphones,
  LockKeyhole,
  RotateCcw,
  Store,
} from 'lucide-react'
import type { HomeContent } from './HomeSections.types'

const media = {
  camera: '/media/home/camera.png',
  rainproof: '/media/home/rainproof.png',
  ceramics: '/media/home/ceramics.png',
  wildflowers: '/media/home/wildflowers.png',
  linen: '/media/home/linen.png',
}

export const homeContent: HomeContent = {
  hero: {
    eyebrow: 'MAY SPOTLIGHT',
    title: 'Discover',
    highlight: 'millions',
    description: "of products you'll love.",
    gallery: [media.camera, media.rainproof, media.wildflowers, media.ceramics],
  },
  categories: [
    { label: 'Electronics', icon: Laptop },
    { label: 'Fashion', icon: Shirt },
    { label: 'Home & Living', icon: Sofa },
    { label: 'Beauty', icon: Sparkles },
    { label: 'Grocery', icon: ShoppingBasket },
    { label: 'Sports', icon: Dumbbell },
    { label: 'Toys & Kids', icon: Store },
    { label: 'Mobile', icon: Smartphone },
    { label: 'Audio', icon: Headphones },
    { label: 'Auto', icon: CarFront },
    { label: 'Books', icon: BookOpen },
    { label: 'Pet', icon: PawPrint },
  ],
  vouchers: [
    { title: '$10 OFF', minimum: 'Min spend $40', code: 'WELCOME10' },
    { title: 'Free Ship', minimum: 'Min spend $20', code: 'FREESHIP' },
    { title: '15% OFF', minimum: 'Cap $20', code: 'MAY15' },
    { title: '$5 OFF', minimum: 'Min spend $30', code: 'LUMEN5' },
  ],
  flashSale: [
    {
      id: 'flash-1',
      name: 'Minimal deck speaker',
      imageUrl: media.rainproof,
      price: '$9',
      discount: '-17%',
      soldPercent: 80,
    },
    {
      id: 'flash-2',
      name: 'Fresh bloom bundle',
      imageUrl: media.wildflowers,
      price: '$61',
      soldPercent: 70,
    },
    {
      id: 'flash-3',
      name: 'Retro camera kit',
      imageUrl: media.camera,
      price: '$113',
      soldPercent: 96,
    },
    {
      id: 'flash-4',
      name: 'Ceramic coffee set',
      imageUrl: media.ceramics,
      price: '$165',
      discount: '-29%',
      soldPercent: 37,
    },
    {
      id: 'flash-5',
      name: 'Weekend linen edit',
      imageUrl: media.linen,
      price: '$217',
      soldPercent: 35,
    },
    {
      id: 'flash-6',
      name: 'Waterproof pack',
      imageUrl: media.rainproof,
      price: '$29',
      soldPercent: 40,
    },
  ],
  trustItems: [
    {
      title: 'Buyer Protection',
      description: 'Full refund if item never arrives',
      icon: ShieldCheck,
    },
    { title: 'Easy 7-day Returns', description: 'Hassle-free on eligible items', icon: RotateCcw },
    { title: 'Verified Sellers', description: 'ID-verified shops only', icon: Store },
    { title: 'Secure Payments', description: 'Encrypted, fraud-monitored', icon: LockKeyhole },
  ],
  featuredSections: [
    {
      title: 'Electronics top picks',
      products: [
        {
          id: 'elec-1',
          name: 'Wireless ANC Headphones â€” Studio Edition',
          imageUrl: media.rainproof,
          price: '$9',
          originalPrice: '$10.80',
          discount: '-17%',
          rating: '4.0',
          sold: '50 sold',
          stockLabel: 'Almost gone',
          flash: true,
          mall: true,
        },
        {
          id: 'elec-2',
          name: 'Mirrorless Camera Travel Set',
          imageUrl: media.camera,
          price: '$165',
          originalPrice: '$231',
          discount: '-29%',
          rating: '4.2',
          sold: '1.1k sold',
          flash: true,
        },
        {
          id: 'elec-3',
          name: 'Studio Audio Weatherproof Case',
          imageUrl: media.wildflowers,
          price: '$81',
          originalPrice: '$129.60',
          discount: '-38%',
          rating: '4.4',
          sold: '2.2k sold',
          flash: true,
        },
        {
          id: 'elec-4',
          name: 'Ceramic Desk Speaker Set',
          imageUrl: media.ceramics,
          price: '$237',
          originalPrice: '$308.10',
          discount: '-23%',
          rating: '4.6',
          sold: '3.3k sold',
          flash: true,
        },
      ],
    },
    {
      title: 'Fashion edit',
      products: [
        {
          id: 'fashion-1',
          name: 'Linen Lounge Set, Oversized Fit',
          imageUrl: media.linen,
          price: '$22',
          rating: '4.1',
          sold: '141 sold',
          stockLabel: 'Almost gone',
        },
        {
          id: 'fashion-2',
          name: 'Weekend Canvas Accessories',
          imageUrl: media.ceramics,
          price: '$178',
          rating: '4.3',
          sold: '1.2k sold',
          mall: true,
        },
        {
          id: 'fashion-3',
          name: 'Natural Linen Essentials',
          imageUrl: media.linen,
          price: '$94',
          rating: '4.5',
          sold: '2.3k sold',
          mall: true,
          freeShipping: true,
        },
        {
          id: 'fashion-4',
          name: 'Outdoor Daylight Edit',
          imageUrl: media.wildflowers,
          price: '$10',
          rating: '4.7',
          sold: '3.4k sold',
        },
      ],
    },
  ],
  electronics: [
    {
      id: 'elec-1',
      name: 'Wireless ANC Headphones — Studio Edition',
      imageUrl: media.rainproof,
      price: '$9',
      originalPrice: '$10.80',
      discount: '-17%',
      rating: '4.0',
      sold: '50 sold',
      stockLabel: 'Almost gone',
      flash: true,
      mall: true,
    },
    {
      id: 'elec-2',
      name: 'Mirrorless Camera Travel Set',
      imageUrl: media.camera,
      price: '$165',
      originalPrice: '$231',
      discount: '-29%',
      rating: '4.2',
      sold: '1.1k sold',
      flash: true,
    },
    {
      id: 'elec-3',
      name: 'Studio Audio Weatherproof Case',
      imageUrl: media.wildflowers,
      price: '$81',
      originalPrice: '$129.60',
      discount: '-38%',
      rating: '4.4',
      sold: '2.2k sold',
      flash: true,
    },
    {
      id: 'elec-4',
      name: 'Ceramic Desk Speaker Set',
      imageUrl: media.ceramics,
      price: '$237',
      originalPrice: '$308.10',
      discount: '-23%',
      rating: '4.6',
      sold: '3.3k sold',
      flash: true,
    },
  ],
  fashion: [
    {
      id: 'fashion-1',
      name: 'Linen Lounge Set, Oversized Fit',
      imageUrl: media.linen,
      price: '$22',
      rating: '4.1',
      sold: '141 sold',
      stockLabel: 'Almost gone',
    },
    {
      id: 'fashion-2',
      name: 'Weekend Canvas Accessories',
      imageUrl: media.ceramics,
      price: '$178',
      rating: '4.3',
      sold: '1.2k sold',
      mall: true,
    },
    {
      id: 'fashion-3',
      name: 'Natural Linen Essentials',
      imageUrl: media.linen,
      price: '$94',
      rating: '4.5',
      sold: '2.3k sold',
      mall: true,
      freeShipping: true,
    },
    {
      id: 'fashion-4',
      name: 'Outdoor Daylight Edit',
      imageUrl: media.wildflowers,
      price: '$10',
      rating: '4.7',
      sold: '3.4k sold',
    },
  ],
  shops: [
    {
      name: 'Lumen Audio Official',
      imageUrl: media.camera,
      rating: '4.9',
      followers: '184k',
      mall: true,
    },
    {
      name: 'Northbloom Living',
      imageUrl: media.wildflowers,
      rating: '4.8',
      followers: '96.3k',
      verified: true,
    },
    { name: 'Kairo Tech', imageUrl: media.rainproof, rating: '4.7', followers: '41k' },
    {
      name: 'Atelier Noor',
      imageUrl: media.ceramics,
      rating: '4.95',
      followers: '312k',
      mall: true,
    },
  ],
  recommended: [
    {
      id: 'rec-1',
      name: 'Weatherproof Everyday Backpack',
      imageUrl: media.rainproof,
      price: '$44',
      discount: '-17%',
      rating: '4.8',
      sold: '2k sold',
      flash: true,
    },
    {
      id: 'rec-2',
      name: 'Relaxed Linen Capsule',
      imageUrl: media.linen,
      price: '$58',
      rating: '4.6',
      sold: '920 sold',
      freeShipping: true,
    },
    {
      id: 'rec-3',
      name: 'Creator Camera Essentials',
      imageUrl: media.camera,
      price: '$229',
      rating: '4.9',
      sold: '510 sold',
      mall: true,
    },
    {
      id: 'rec-4',
      name: 'Artisan Table Set',
      imageUrl: media.ceramics,
      price: '$35',
      discount: '-33%',
      rating: '4.7',
      sold: '1.4k sold',
    },
  ],
  newArrivals: [
    {
      id: 'new-1',
      name: 'Wildflower Home Fragrance',
      imageUrl: media.wildflowers,
      price: '$18',
      rating: '4.9',
      sold: 'New',
    },
    {
      id: 'new-2',
      name: 'Linen Travel Organizer',
      imageUrl: media.linen,
      price: '$26',
      rating: '4.8',
      sold: 'New',
      freeShipping: true,
    },
    {
      id: 'new-3',
      name: 'Compact Film Camera',
      imageUrl: media.camera,
      price: '$129',
      rating: '4.7',
      sold: 'New',
      mall: true,
    },
    {
      id: 'new-4',
      name: 'Handmade Mug Collection',
      imageUrl: media.ceramics,
      price: '$32',
      rating: '5.0',
      sold: 'New',
    },
  ],
}
